### ISSUE TITLE
проблема

### ISSUE THREAD

**Issue by Pak2023** [zcc39r/ung#2]
Здравствуйте! У меня не работает скрипт ни в Хроме, ни в Файерфоксе. Не появляется кнопка для скачивания данных. Раньше скрипт запускался в Файерфоксе нормально. В чем может быть проблема?

**Comment by zcc39r** [comment]
В ФФ я часто наблюдаю проблему активации Tampermonkey после запуска браузера. В этом случае помогает отключение и включение этого плагина. В общем надо убедиться, что подсистема управления пользовательскими скриптами установлена и работает должным образом, а скрипт установлен.

**Comment by Pak2023** [comment]
Расширение отключал-включал, страницу перезагружал. Все равно кнопка для скачивания не видна, хотя при работе скрипта заметно смещение влево на странице элемента фильтр. Сам скрипт срабатывает. Я вручную дописал "ссылка". При нажатии на нее открывается страница с собранными данными.
![genotek](https://user-images.githubusercontent.com/125118188/218306151-1b9d21d8-a1f6-4e6d-b40f-69d5f74a4b98.png)

**Comment by zcc39r** [comment]
Возможно, шрифт не подгрузился.
